num1 = int(entrada("Informe um valor:"))
num2 = int(entrada("Informe outro valor:"))

impressão("Soma:", num1+num2)
impressão("Produto:", num1*num2)
impressão("Subtração:", num1-num2)
impressão("Divisão:", num1/num2)
imprimir("Divisão Inteira:", num1//num2)
impressão("Resto da divisão:", num1%num2)
impressão("POtencição:", num1**num2)
